#version: "3.8"
version: "3.3"
services:

  # MONGO
  mongo:
    container_name: mongo
    build: ./mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    networks:
      bananakw:
        aliases:
          - mongo_net

  # PYTHON BOT
  python_bot:
    container_name: python_bot
    build: ./python_bot
    ports:
      - "8005:8000"
    environment:
      - TOKEN=${TELEGRAM_BOT_API_TOKEN}
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - HOST=${HOST}
    volumes:
      - ./python_bot/src:/usr/src/app/src
    depends_on:
      - mongo
    links: # TODO: нужно ли? Проверить как будет работать без этого
      - mongo
    networks:
      bananakw:
        aliases:
          - python_bot_net

  # PYTHON API
  pythonapi:
    container_name: pythonapi
    build: ./python_api
#    ports:
#      - "5000:5000"
    expose:
      - 5000
    ports:
      - 5000
    environment:
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
    volumes:
      - ./python_api/src:/usr/src/app/src
    depends_on:
      - mongo
#      - bot_nginx
#    command: /usr/local/bin/gunicorn -w 2 -b :5000 app:app
    networks:
      bananakw:
        aliases:
          - pythonapi_net

  # NGINX
  bot_nginx:
    container_name: bot_nginx
    build: ./nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/src:/data/www/banana-kw.local
      - ./nginx/src:/data/www/gedeon.host
      - ./nginx/logs:/etc/nginx/logs
    ports:
      - "80:80"
    depends_on:
      - pythonapi
#    links:
#      - pythonapi:pythonapi
    networks:
      bananakw:
        aliases:
          - bot_nginx_net

networks:
  bananakw:
    name: bananakw
    driver: bridge