version: "3.8"
services:

  # MONGO
  mongo:
    container_name: mongo
    build: ./mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: "links"
    networks:
      backend:
        aliases:
          - mongo_net

  # PYTHON BOT
  python_bot:
    container_name: python_bot
    build: ./python_bot
    ports:
      - "8005:8000"
    environment:
      - TOKEN=${TELEGRAM_BOT_API_TOKEN}
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_DATABASE=links
    volumes:
      - ./python_bot/src:/usr/src/app/src
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      backend:
        aliases:
          - python_bot_net

  # PYTHON API
#  python_api:
#    container_name: python_api
#    build: ./python_api
#    ports:
#      - "8000:8000"
#    networks:
#      backend:
#        aliases:
#          - python_api_net

  # NGINX
#  nginx:
#    container_name: nginx
#    build: ./nginx
#    volumes:
#      - ./nginx/templates:/etc/nginx/templates
#      - ./nginx/logs:/etc/nginx/logs
#    ports:
#      - "80:80"
#    networks:
#      backend:
#        aliases:
#          - nginx_net

networks:
  backend: